"""
PDXLang 代码生成规则

此模块包含从游戏官方文档自动生成的规则
"""

# 标识符分类
from .identifiers import SHARED_IDENTIFIERS, TRIGGER_IDENTIFIERS_EXCLUSIVE, EFFECT_IDENTIFIERS_EXCLUSIVE, SCOPES_IDENTIFIERS

# Trigger 和 Effect 规则
from .trigger_rules import ALL_TRIGGERS
from .effect_rules import ALL_EFFECTS

# Scope 规则
from .scope_rules import SCOPES

# Modifier 规则
from .modifier_rules import MODIFIER_CATEGORIES, ALL_MODIFIERS, MODIFIERS_AI_ECONOMY, MODIFIERS_ARMIES, MODIFIERS_ASTRAL_RIFT, MODIFIERS_CIVILIAN_SHIPS, MODIFIERS_COUNTRIES, MODIFIERS_DEPOSITS, MODIFIERS_ECONOMIC_UNITS, MODIFIERS_ESPIONAGE, MODIFIERS_FEDERATIONS, MODIFIERS_FLEETS, MODIFIERS_HABITABILITY, MODIFIERS_JOB, MODIFIERS_LEADERS, MODIFIERS_MEGASTRUCTURES, MODIFIERS_MILITARY_SHIPS, MODIFIERS_NONE, MODIFIERS_ORBITAL_STATIONS, MODIFIERS_OWNED_SHIPS, MODIFIERS_PLANETS, MODIFIERS_POP_FACTIONS, MODIFIERS_POPS, MODIFIERS_SCIENCE_SHIPS, MODIFIERS_SHIP_DESIGN_STATS, MODIFIERS_SHIPS, MODIFIERS_SPACE_STATIONS, MODIFIERS_STAR_SYSTEMS, MODIFIERS_STARBASES, MODIFIERS_TRANSPORT_SHIPS
