"""
PDXLang 标识符分类

此文件由 tools/generate_python_rules.py 自动生成
不要手动编辑！
"""

# 共享标识符（同时存在于 trigger 和 effect 中）
SHARED_IDENTIFIERS = frozenset({
    'closest_system', 'custom_tooltip', 'debug_break', 'else', 'else_if', 'if', 'inverted_switch', 
    'log', 'switch', 'trait_of_species', 'traits_available_for_species',
})

# Trigger 独占标识符
TRIGGER_IDENTIFIERS_EXCLUSIVE = frozenset({
    'acquired_specimen_count', 'additional_crisis_strength', 'agreement_preset', 
    'ai_colonize_plans', 'ai_terraform_plans', 'ai_wants_to_negotiate_agreement', 
    'allowed_crisis_type', 'always', 'and', 'any_active_first_contact', 'any_agreement', 
    'any_ambient_object', 'any_archaeological_site', 'any_associate', 'any_astral_rift', 
    'any_attacker', 'any_available_debris', 'any_bypass', 'any_bypass_in_system', 
    'any_combatant_fleet', 'any_controlled_fleet', 'any_controlled_planet', 'any_controlled_ship', 
    'any_cosmic_storm', 'any_cosmic_storm_end_position', 'any_cosmic_storm_start_position', 
    'any_council_member', 'any_country', 'any_country_neighbor_to_system', 'any_defender', 
    'any_deposit', 'any_enslaved_species', 'any_envoy', 'any_espionage_asset', 
    'any_espionage_operation', 'any_exhibit', 'any_existing_species_traits', 'any_federation', 
    'any_federation_ally', 'any_first_contact', 'any_fleet_in_orbit', 'any_fleet_in_system', 
    'any_galaxy_fleet', 'any_galaxy_planet', 'any_galaxy_sector', 'any_galaxy_species', 
    'any_galcom_member', 'any_ground_combat_attacker', 'any_ground_combat_defender', 
    'any_job_pop_group', 'any_megastructure', 'any_member', 'any_moon', 'any_neighbor_country', 
    'any_neighbor_system', 'any_neighbor_system_euclidean', 'any_observed_pre_ftl_within_border', 
    'any_orbital_station', 'any_owned_army', 'any_owned_design', 'any_owned_fleet', 
    'any_owned_leader', 'any_owned_megastructure', 'any_owned_nonprimary_starbase', 
    'any_owned_planet', 'any_owned_pop_group', 'any_owned_pop_job', 'any_owned_pop_species', 
    'any_owned_sector', 'any_owned_ship', 'any_owned_species', 'any_owned_starbase', 
    'any_owned_storm_influence_field', 'any_planet_army', 'any_planet_within_border', 
    'any_playable_country', 'any_pool_leader', 'any_pop_faction', 'any_pre_ftl_within_border', 
    'any_relation', 'any_rim_system', 'any_rival_country', 'any_ship_in_system', 'any_situation', 
    'any_species_pop_group', 'any_spynetwork', 'any_starbase_in_system', 'any_subject', 
    'any_system', 'any_system_added_to_storm', 'any_system_ambient_object', 'any_system_colony', 
    'any_system_in_cosmic_storm_influence_field', 'any_system_megastructure', 'any_system_planet', 
    'any_system_removed_from_storm', 'any_system_with_aura', 'any_system_within_border', 
    'any_system_within_storm', 'any_targeting_situation', 'any_trait_available_for_species', 
    'any_trait_of_species', 'any_war', 'any_war_participant', 'army_type', 
    'artificial_pops_last_month_growth', 'astral_rift_relative_difficulty', 
    'astral_rifts_completed', 'attacker_war_exhaustion', 'attunement', 'balance', 
    'bioship_can_grow', 'branch_office_value', 'built_on_planet', 'calc_true_if', 
    'can_access_system', 'can_afford_special_offer', 'can_be_crisis_terraformed', 
    'can_be_reanimated', 'can_be_upgraded', 'can_buy_on_market', 'can_change_policy', 
    'can_colonize', 'can_control_access_for', 'can_copy_random_tech_from', 'can_declare_war', 
    'can_give_specimen', 'can_go_mia', 'can_have_first_contact_site_with', 'can_join_factions', 
    'can_live_on_planet', 'can_lock_be_renewed', 'can_research_technology', 'can_research_tier', 
    'can_set_policy', 'can_set_situation_approach', 'can_work_specific_job', 'capital_tier', 
    'caravaneers_enabled', 'category_last_picked_tradition', 
    'check_economic_production_modifier_for_job', 'check_galaxy_setup_value', 
    'check_modifier_value', 'check_pop_faction_parameter', 'check_variable', 
    'check_variable_arithmetic', 'city_graphical_culture', 'civics_count', 'colony_age', 
    'colony_age_years', 'colony_type', 'command_limit', 'compare_distance', 'conditional_tooltip', 
    'controlled_colonizable', 'controlled_systems', 'cosmic_storm_influence_value', 
    'cosmic_storm_system_influence', 'council_agenda_progress', 'council_agenda_progress_percent', 
    'council_legitimacy', 'count_active_first_contact', 'count_agreement', 'count_ambient_object', 
    'count_archaeological_site', 'count_associate', 'count_astral_rift', 'count_attacker', 
    'count_available_debris', 'count_bypass', 'count_bypass_in_system', 'count_combatant_fleet', 
    'count_controlled_fleet', 'count_controlled_planet', 'count_controlled_ship', 
    'count_cosmic_storm', 'count_cosmic_storm_end_position', 'count_cosmic_storm_start_position', 
    'count_council_member', 'count_country', 'count_country_neighbor_to_system', 'count_defender', 
    'count_deposit', 'count_deposits', 'count_end_cycle_systems', 'count_enslaved_species', 
    'count_envoy', 'count_espionage_asset', 'count_espionage_operation', 'count_exact_species', 
    'count_exhibit', 'count_existing_species_traits', 'count_federation', 'count_federation_ally', 
    'count_first_contact', 'count_fleet_in_orbit', 'count_fleet_in_system', 'count_galaxy_fleet', 
    'count_galaxy_planet', 'count_galaxy_sector', 'count_galaxy_species', 'count_galcom_member', 
    'count_ground_combat_attacker', 'count_ground_combat_defender', 'count_job_pop_group', 
    'count_megastructure', 'count_member', 'count_moon', 'count_neighbor_country', 
    'count_neighbor_system', 'count_neighbor_system_euclidean', 
    'count_observed_pre_ftl_within_border', 'count_orbital_station', 'count_owned_army', 
    'count_owned_design', 'count_owned_fleet', 'count_owned_leader', 'count_owned_megastructure', 
    'count_owned_nonprimary_starbase', 'count_owned_planet', 'count_owned_pop_amount', 
    'count_owned_pop_group', 'count_owned_pop_job', 'count_owned_pop_species', 'count_owned_sector', 
    'count_owned_ship', 'count_owned_species', 'count_owned_starbase', 
    'count_owned_storm_influence_field', 'count_owned_workforce', 'count_planet_army', 
    'count_planet_within_border', 'count_playable_country', 'count_pool_leader', 
    'count_pop_faction', 'count_potential_war_participants', 'count_pre_ftl_within_border', 
    'count_relation', 'count_rim_system', 'count_rival_country', 'count_ship_in_system', 
    'count_ship_size_in_system', 'count_situation', 'count_species', 'count_species_pop_group', 
    'count_species_traits', 'count_spynetwork', 'count_starbase_buildings', 
    'count_starbase_in_system', 'count_starbase_modules', 'count_starbase_sizes', 'count_subject', 
    'count_system', 'count_system_added_to_storm', 'count_system_ambient_object', 
    'count_system_colony', 'count_system_in_cosmic_storm_influence_field', 
    'count_system_megastructure', 'count_system_planet', 'count_system_removed_from_storm', 
    'count_system_with_aura', 'count_system_within_border', 'count_system_within_storm', 
    'count_systems_with_aura', 'count_targeting_situation', 'count_tech_options', 
    'count_trait_available_for_species', 'count_trait_of_species', 'count_unlocked_active_accords', 
    'count_used_naval_cap', 'count_war', 'count_war_participant', 'count_war_participants', 
    'current_awareness_level', 'current_situation_approach', 'current_stage', 'custom_progress', 
    'custom_tooltip_fail', 'custom_tooltip_success', 'cutholoids_scaling', 'days_passed', 
    'def_war_exhaustion_sum', 'defender_war_exhaustion', 'diplomacy_weight', 'distance', 
    'distance_to_capital', 'distance_to_core_percent', 'distance_to_empire', 'empire_size', 
    'empire_sprawl', 'empire_sprawl_cap_fraction', 'empire_sprawl_over_cap', 
    'enclave_capacity_left', 'end_game_years_passed', 'envoy_opinion_change', 'ethos', 'exists', 
    'expenses', 'exploitable_planets', 'faction_approval', 'fail_text', 'federation_cohesion', 
    'federation_cohesion_growth', 'federation_experience', 'federation_level', 'fleet_integrity', 
    'fleet_power', 'fleet_size', 'former_citizenship_type', 'former_colonization_control_type', 
    'former_living_standard_type', 'former_migration_control_type', 'former_military_service_type', 
    'former_population_control_type', 'former_purge_type', 'former_slavery_type', 'free_amenities', 
    'free_branch_office_building_slots', 'free_building_slots', 'free_district_slots', 
    'free_housing', 'free_jobs', 'free_jobs_of_type', 'galactic_community_rank', 
    'galactic_defense_force_exists', 'galaxy_percentage', 'galaxy_shape', 'galaxy_size', 'gender', 
    'get_attunement_points_for', 'get_councilor_level', 'governors_skill_in_system', 
    'graphical_culture', 'habitability', 'happiness', 'happiness_planet', 'has_access_fleet', 
    'has_active_building', 'has_active_event', 'has_active_first_contact_with', 'has_active_focus', 
    'has_active_specialization', 'has_active_tradition', 'has_agenda_selected', 
    'has_agreement_flag', 'has_ai_expansion_plan', 'has_ai_personality', 
    'has_ai_personality_behaviour', 'has_ambient_object_flag', 'has_anomaly', 
    'has_any_federation_law_in_category', 'has_any_flag', 'has_any_megastructure', 
    'has_any_overlord', 'has_any_strategic_resource', 'has_archaeology_flag', 
    'has_armor_percentage', 'has_army', 'has_army_flag', 'has_ascension_perk', 
    'has_association_status', 'has_asteroid_belt', 'has_astral_rift', 'has_astral_rift_flag', 
    'has_attitude_behavior', 'has_authority', 'has_auto_move_target', 'has_available_jobs', 
    'has_available_spy_power', 'has_awareness', 'has_background_job', 'has_base_skill', 
    'has_branch_office', 'has_building', 'has_building_construction', 'has_built_species', 
    'has_casus_belli', 'has_citizenship_rights', 'has_citizenship_type', 'has_civic', 
    'has_civic_in_slot', 'has_claim', 'has_climate', 'has_cloaking_detection', 
    'has_cloaking_strength', 'has_closed_borders', 'has_colonization_control', 
    'has_commercial_pact', 'has_communications', 'has_completed_event_chain', 
    'has_completed_event_chain_counter', 'has_completed_focus', 
    'has_completed_special_project_in_log', 'has_component', 'has_country_flag', 
    'has_country_resource', 'has_covenant', 'has_crisis_level', 'has_crisis_perk', 
    'has_current_purge', 'has_defensive_pact', 'has_deficit', 'has_deposit', 'has_deposit_category', 
    'has_deposit_flag', 'has_deposit_for', 'has_design_flag', 'has_designation', 
    'has_diplo_migration_treaty', 'has_district', 'has_dna', 'has_edict', 'has_election_type', 
    'has_embassy', 'has_environmental_effects', 'has_envoy_cooldown', 'has_envoy_task', 
    'has_espionage_asset', 'has_espionage_asset_flag', 'has_espionage_category', 
    'has_espionage_operation_flag', 'has_espionage_type', 'has_established_contact', 'has_ethic', 
    'has_event_chain', 'has_existing_ship_design', 'has_experience', 'has_extorted_faction', 
    'has_faction', 'has_failed_special_project_in_log', 'has_federation', 'has_federation_flag', 
    'has_federation_law', 'has_federation_perk', 'has_federation_setting', 'has_federation_type', 
    'has_first_contact_flag', 'has_fleet_flag', 'has_fleet_order', 'has_forbidden_jobs', 
    'has_galactic_community_emissary', 'has_galactic_custodian', 'has_galactic_emperor', 
    'has_global_flag', 'has_government', 'has_ground_combat', 'has_highest_technology_score', 
    'has_holding', 'has_hp', 'has_hp_percentage', 'has_hyperlane_to', 'has_intel', 
    'has_intel_level', 'has_intel_report', 'has_invalid_civic', 'has_job_category', 'has_job_type', 
    'has_leader_flag', 'has_living_standard', 'has_lock', 'has_loyalty', 'has_max_armor_hp', 
    'has_max_hp', 'has_megastructure', 'has_megastructure_flag', 'has_menace_perk', 
    'has_migration_access', 'has_migration_control', 'has_military_service_type', 
    'has_mining_station', 'has_mission', 'has_modifier', 'has_monthly_income', 
    'has_monthly_loyalty', 'has_moon', 'has_most_attunement', 'has_natural_wormhole', 
    'has_next_pre_ftl_age', 'has_non_aggression_pact', 'has_notification_modifier', 
    'has_observation_outpost', 'has_opinion_modifier', 'has_orbital_bombardment', 
    'has_orbital_bombardment_stance', 'has_orbital_station', 'has_origin', 'has_overlord', 
    'has_owner', 'has_passed_resolution', 'has_patron_aura', 'has_patron_counter', 
    'has_patron_relation', 'has_picked_auto_mod_habitability', 'has_planet_class', 
    'has_planet_flag', 'has_planet_modifier', 'has_planetary_ascension_tier', 
    'has_point_of_interest', 'has_policy_flag', 'has_pop_faction_flag', 'has_pop_flag', 
    'has_pop_group_flag', 'has_population_control', 'has_potential_claims', 'has_pre_ftl_age', 
    'has_pre_ftl_trade', 'has_presence', 'has_psionic_aura', 'has_purge_type', 'has_relation_flag', 
    'has_relic', 'has_research_agreement', 'has_research_station', 'has_resource', 'has_ring', 
    'has_rival', 'has_role', 'has_ruler_trait', 'has_same_ethos', 
    'has_secret_fealty_from_subject_of', 'has_secret_fealty_with', 'has_sector_flag', 
    'has_sector_type', 'has_seen_any_bypass', 'has_seen_specific_bypass', 'has_sensor_link_from', 
    'has_shield_hp', 'has_shield_percentage', 'has_ship_flag', 'has_ship_owner_type', 
    'has_situation_flag', 'has_slavery_type', 'has_special_project', 'has_specialist_perk', 
    'has_species_flag', 'has_specimen', 'has_spy_power', 'has_spynetwork', 'has_spynetwork_flag', 
    'has_spynetwork_value', 'has_stage_modifier', 'has_stale_intel', 'has_star_flag', 
    'has_starbase_building', 'has_starbase_flag', 'has_starbase_module', 'has_starbase_size', 
    'has_status', 'has_storm_flag', 'has_strategic_resource', 'has_subject', 'has_surveyed_class', 
    'has_tech_option', 'has_technology', 'has_term_value', 'has_total_civic_points', 
    'has_total_skill', 'has_tradition', 'has_trait', 'has_truce', 'has_unlocked_all_traditions', 
    'has_unlocked_council_positions', 'has_unused_civic_points', 'has_valid_ai_personality', 
    'has_valid_civic', 'has_war_flag', 'has_war_goal', 'hidden_progress', 'hidden_trigger', 
    'highest_threat', 'host_has_dlc', 'ideal_planet_class', 'imperial_authority', 'in_breach_of', 
    'income', 'inherits_parent_rights', 'inner_radius', 'intel', 'intel_level', 'is_action_active', 
    'is_active_resolution', 'is_advisor_active', 'is_ai', 'is_alliance_fleet', 
    'is_ambient_object_type', 'is_angry_to', 'is_archetype', 'is_army', 'is_arrogant_to', 
    'is_artificial', 'is_asteroid', 'is_astral_rift_explored', 'is_astral_rift_pool_empty', 
    'is_astral_scar', 'is_at_war', 'is_at_war_with', 'is_aura_intensity_level', 
    'is_background_planet', 'is_being_assimilated', 'is_being_integrated_by', 'is_being_repaired', 
    'is_belligerent_to', 'is_berserker_to', 'is_blocker', 'is_bottleneck_system', 'is_bridge', 
    'is_bypass_type', 'is_capital', 'is_capital_system', 
    'is_capitals_connected_through_relay_network', 'is_cardinal_patron', 'is_civilian', 
    'is_cloaked', 'is_colonizable', 'is_colony', 'is_constructing', 'is_controlled_by', 
    'is_cordial_to', 'is_councilor', 'is_councilor_type', 'is_counter_espionage', 'is_country', 
    'is_country_type', 'is_criminal_syndicate', 'is_crises_allowed', 'is_current_excavator_fleet', 
    'is_current_first_contact_stage', 'is_current_stage_clues', 'is_current_stage_difficulty', 
    'is_custodial_to', 'is_custom_capital_location', 'is_damaged', 'is_default_species', 
    'is_defensive_army', 'is_deposit_type', 'is_designable', 'is_difficulty', 'is_disabled', 
    'is_disloyal_to', 'is_dismissive_to', 'is_domineering_to', 'is_enigmatic_to', 
    'is_espionage_operation_auto_accept_events', 'is_espionage_operation_chapter', 
    'is_espionage_operation_days_to_next_die_roll', 'is_espionage_operation_difficulty', 
    'is_espionage_operation_last_die_result', 'is_espionage_operation_score', 
    'is_espionage_operation_score_no_die', 'is_ethic_represented_on_council', 'is_event_leader', 
    'is_exact_same_species', 'is_exhibit_active', 'is_faction_extorted', 'is_federation_leader', 
    'is_fleet_idle', 'is_forced_friendly', 'is_forced_neutral', 'is_friendly_to', 
    'is_from_proxy_war', 'is_galactic_community_formed', 'is_galactic_community_member', 
    'is_galactic_council_established', 'is_galactic_custodian', 'is_galactic_emperor', 
    'is_garrison', 'is_growth_complete', 'is_guaranteeing', 'is_harming_relations_with', 'is_heir', 
    'is_hidden', 'is_homeworld', 'is_hostile', 'is_hostile_to', 'is_ideal', 'is_ideal_planet_class', 
    'is_idle', 'is_immortal', 'is_imperious_to', 'is_improving_relations_with', 
    'is_in_breach_of_any', 'is_in_cluster', 'is_in_combat', 'is_in_domain', 'is_in_federation_with', 
    'is_in_frontier_space', 'is_in_frontline', 'is_in_sensor_range', 
    'is_in_sensor_range_of_country', 'is_infertile', 'is_influence_center', 'is_inside_border', 
    'is_inside_nebula', 'is_inside_storm', 'is_ironman', 'is_job_of_pop_category', 
    'is_last_acquired_specimen', 'is_last_acquired_specimen_from_trade', 
    'is_last_acquired_specimen_rarity', 'is_last_building_changed_capital', 
    'is_last_increased_tech_category', 'is_last_increased_tech_rare', 
    'is_last_increased_tech_repeatable', 'is_last_lost_relic', 'is_last_received_relic', 
    'is_leader_tier', 'is_leased', 'is_loyal_to', 'is_majority_species', 'is_market_leader', 
    'is_megastructure_type', 'is_mobile', 'is_moon', 'is_multiplayer', 'is_neighbor_of', 
    'is_neutral_to', 'is_occupied_flag', 'is_offer_terms_actual', 'is_on_border', 
    'is_on_galaxy_map', 'is_on_market', 'is_on_slave_market', 'is_orbiting_star', 
    'is_original_owner', 'is_overlord', 'is_overlord_to', 'is_owned_by', 
    'is_part_of_galactic_council', 'is_patronizing_to', 'is_paused', 'is_permanent_councillor', 
    'is_pirate', 'is_planet', 'is_planet_class', 'is_point_of_interest', 'is_pop_category', 
    'is_pop_faction_type', 'is_preferred_patron', 'is_preferred_weapons', 'is_preventing_anomaly', 
    'is_primary_star', 'is_primitive', 'is_proposing_resolution', 'is_protective_to', 
    'is_reanimated', 'is_researching_any_technology', 'is_researching_special_project', 
    'is_researching_technology', 'is_rim_system', 'is_ringworld', 'is_rival', 'is_robot_pop', 
    'is_robot_pop_group', 'is_robotic', 'is_ruler', 'is_running_espionage_operation', 
    'is_same_empire', 'is_same_species', 'is_same_species_class', 'is_same_value', 'is_sapient', 
    'is_scope_set', 'is_scope_type', 'is_scope_valid', 'is_scripted_terraforming', 
    'is_sector_capital', 'is_ship', 'is_ship_category', 'is_ship_class', 'is_ship_size', 
    'is_site_at_stage', 'is_site_completed', 'is_site_current_stage_score', 
    'is_site_current_stage_score_no_die', 'is_site_days_to_next_die_roll', 
    'is_site_last_die_result', 'is_site_last_excavator', 'is_site_locked', 'is_site_type', 
    'is_site_under_excavation', 'is_situation_type', 'is_space_fauna', 'is_species', 
    'is_species_class', 'is_specimen_category', 'is_specimen_rarity', 'is_spynetwork_level', 
    'is_spynetwork_max_level', 'is_star', 'is_star_class', 'is_starbase_building_building', 
    'is_starbase_building_module', 'is_starbase_type', 'is_storm_active_in_storm_sector', 
    'is_storm_type', 'is_subject', 'is_subspecies', 'is_surveyed', 
    'is_system_connected_to_relay_network', 'is_terraformed', 'is_terraforming', 'is_threatened_to', 
    'is_total_war', 'is_tutorial_level', 'is_under_colonization', 
    'is_under_open_technological_enlightenment', 'is_under_societal_enlightenment', 
    'is_under_stratified_technological_enlightenment', 'is_unfriendly_to', 'is_upgrading', 
    'is_valid', 'is_variable_set', 'is_voting_on_resolution', 'is_war_leader', 'is_war_participant', 
    'is_within_borders_of', 'is_years_since_community_formation', 
    'is_years_since_council_establishment', 'last_activated_relic', 'last_building_changed', 
    'last_changed_policy', 'last_changed_species_rights_type', 
    'last_completed_special_project_has_research_cost', 'last_district_changed', 
    'last_increased_tech', 'last_lost_relic', 'last_received_relic', 
    'last_resolution_category_changed', 'last_resolution_changed', 'leader_age', 'leader_class', 
    'leader_lifespan', 'leader_years_of_service', 'lease_days', 'lgate_enabled', 'local_has_dlc', 
    'logged_in_to_pdx_account', 'market_resource_price', 'max_naval_capacity', 
    'max_starbase_capacity', 'member_of_faction', 'mid_game_years_passed', 'mission_progress', 
    'monthly_intensity_increase', 'must_research', 'must_scavenge', 'name_list_category', 'nand', 
    'nb_pop_exact_species', 'nor', 'not', 'num_active_gateways', 'num_ai_empires_setting', 
    'num_armies', 'num_ascension_perk_slots', 'num_ascension_perks', 'num_assigned_jobs', 
    'num_associates', 'num_asteroid_belts', 'num_buildings', 'num_candidate_supported', 
    'num_closed_borders', 'num_commercial_pacts', 'num_communications', 
    'num_cosmic_storm_early_game_spawn_chance_scale_setting', 
    'num_cosmic_storm_early_game_spawn_max_cap_setting', 
    'num_cosmic_storm_late_game_spawn_chance_scale_setting', 
    'num_cosmic_storm_late_game_spawn_max_cap_setting', 
    'num_cosmic_storm_mid_game_spawn_chance_scale_setting', 
    'num_cosmic_storm_mid_game_spawn_max_cap_setting', 
    'num_cosmic_storm_spawn_cooldown_scale_setting', 'num_cosmic_storms', 
    'num_cosmic_storms_encountered', 'num_council_positions', 'num_custom_1_techs', 
    'num_custom_2_techs', 'num_custom_3_techs', 'num_dangerous_techs', 'num_defensive_pacts', 
    'num_deposits', 'num_districts', 'num_empires', 'num_energy', 'num_engineering', 
    'num_envoys_to_federation', 'num_envoys_to_galcom', 'num_espionage_assets', 'num_ethics', 
    'num_fallen_empires', 'num_fallen_empires_setting', 'num_favors', 'num_fleets', 
    'num_free_districts', 'num_galaxy_systems', 'num_guaranteed_colonies', 'num_guarantees', 
    'num_housing', 'num_insight_techs', 'num_killed_ships', 'num_leader_traits', 
    'num_marauder_empires_to_spawn', 'num_members', 'num_migration_pacts', 'num_minerals', 
    'num_modifiers', 'num_moons', 'num_negative_traits', 'num_neighbor_systems', 
    'num_non_aggression_pacts', 'num_owned_active_gateways', 'num_owned_leaders', 
    'num_owned_planets', 'num_owned_relics', 'num_physics', 'num_planetary_ascension_tiers', 
    'num_planets_in_system', 'num_pops_assigned_to_job', 'num_positive_traits', 'num_proxy_war', 
    'num_rare_techs', 'num_repeatable_techs', 'num_research_agreements', 'num_researched_techs', 
    'num_researched_techs_of_tier', 'num_rivals', 'num_sectors', 'num_ships', 'num_ships_in_debris', 
    'num_society', 'num_species', 'num_starbases', 'num_storm_exploitation_buildings', 
    'num_support_independence', 'num_taken_planets', 'num_tradition_categories', 'num_trait_points', 
    'num_traits', 'num_truces', 'num_uncleared_blockers', 'num_unemployed', 
    'num_unique_cosmic_storms_encountered', 'num_unique_species', 'num_vivarium_slots', 'num_zones', 
    'off_war_exhaustion_sum', 'opinion', 'opinion_level', 'opposing_ethics_divergence', 'or', 
    'organic_pops_last_month_growth', 'original_owner', 'owns_any_bypass', 
    'patron_has_all_accords_unlocked', 'perc_communications_with_playable', 'planet_crime', 
    'planet_devastation', 'planet_garrison_strength', 'planet_happiness_above_threshold', 
    'planet_resource_compare', 'planet_size', 'planet_stability', 'pop_amount_percentage', 
    'pop_group_crime', 'pop_group_has_ethic', 'pop_group_has_happiness', 'pop_group_has_trait', 
    'pop_group_size', 'pop_has_ethic', 'pop_has_happiness', 'pop_maintenance_cost', 
    'position_on_current_resolution', 'position_on_last_resolution', 'recently_lost_war', 
    'relative_encryption_decryption', 'relative_power', 'resource_expenses_compare', 
    'resource_income_compare', 'resource_income_to_expenditure_balance_ratio', 
    'resource_revenue_compare', 'resource_stockpile_compare', 'reverse_has_relation_flag', 
    'running_balance', 'scientist_count', 'ship_size_cost_resource_percent', 'ship_size_multiplier', 
    'simple_progress', 'situation_monthly_progress', 'situation_progress', 'specialist_tier', 
    'species_gender', 'species_has_happiness_with_owner', 'species_modifiers_only', 
    'species_portrait', 'starbase_buildable_is_in_queue_before', 'starting_system', 
    'stored_engineering_points', 'stored_physics_points', 'stored_society_points', 
    'subject_can_diplomacy', 'subjects', 'success_text', 'support', 'tech_unlocked_ratio', 
    'terraformed_by', 'text', 'their_opinion', 'timed_flag_days_left', 
    'total_country_workforce_with_job_tag', 'total_system_workforce_with_job_tag', 
    'total_workforce_with_job_tag', 'trait_has_all_tags', 'trait_has_any_tag', 'triumph_days_left', 
    'trust', 'upgrade_days_left', 'uplift_is_archetype', 'used_defense_platform_capacity_percent', 
    'used_favors_on_last_resolution', 'used_naval_capacity_integer', 'used_naval_capacity_percent', 
    'used_starbase_capacity_integer', 'used_starbase_capacity_percent', 'uses_district_set', 
    'uses_ship_category', 'using_war_goal', 'valid_planet_killer_target', 'vassals', 
    'voidworms_scaling', 'war_begun_num_fleets_gone_mia', 'won_the_game', 'would_join_war', 
    'years_of_peace', 'years_passed',
})

# Effect 独占标识符
EFFECT_IDENTIFIERS_EXCLUSIVE = frozenset({
    'abort_situation', 'abort_special_project', 'accept_covenant', 'activate_crisis_progression', 
    'activate_fog_machine', 'activate_gateway', 'activate_saved_leader', 'add_age', 'add_anomaly', 
    'add_ascension_perk', 'add_associate_member', 'add_asteroid_belt', 'add_attunement', 
    'add_aura_intensity', 'add_awareness', 'add_blocker', 'add_building', 'add_casus_belli', 
    'add_claims', 'add_cohesion', 'add_colony_progress', 'add_council_agenda_progress', 
    'add_council_agenda_progress_percent', 'add_custodian_term_days', 'add_deposit', 
    'add_deposit_category_effect', 'add_district', 'add_edict', 'add_espionage_information', 
    'add_event_chain_counter', 'add_expedition_log_entry', 'add_experience', 'add_favors', 
    'add_federation_experience', 'add_focus_progress', 'add_global_ship_design', 'add_growth', 
    'add_holding', 'add_hyperlane', 'add_imperial_authority', 'add_intel', 'add_intel_report', 
    'add_loyalty', 'add_mission_counter', 'add_mission_progress', 'add_modifier', 
    'add_monthly_resource_mult', 'add_notification_modifier', 'add_opinion_modifier', 
    'add_patron_objective_counter', 'add_permanent_councillor', 'add_planet_devastation', 
    'add_pop_amount', 'add_random_non_blocker_deposit', 'add_random_research_option', 'add_relic', 
    'add_research_option', 'add_resource', 'add_resource_from_debris', 'add_seen_bypass', 
    'add_seen_bypass_type', 'add_ship_design', 'add_situation_progress', 'add_skill', 
    'add_skill_without_trait_selection', 'add_spy_network_level', 'add_stage_clues', 
    'add_stage_modifier', 'add_starbase_component', 'add_static_war_exhaustion', 
    'add_tech_progress', 'add_terraform_progress', 'add_terraformation_total_time_mult', 
    'add_threat', 'add_timed_trait', 'add_timeline_event', 'add_to_galactic_community', 
    'add_to_galactic_community_no_message', 'add_to_galactic_council', 'add_to_vivarium', 
    'add_tradition', 'add_trait', 'add_trust', 'add_variable', 'add_victory_score', 'add_zone', 
    'advanced_authority_refresh', 'agreement_event', 'assign_espionage_asset', 'assign_leader', 
    'astral_rift_event', 'atmosphere_intensity', 'atmosphere_width', 'auto_follow_fleet', 
    'auto_move_to_planet', 'begin_event_chain', 'blocked_deposit', 'break', 'bypass_event', 
    'calculate_modifier', 'cancel_resolution', 'cancel_terraformation', 'ceiling_variable', 
    'change_background_ethic', 'change_background_job', 'change_colony_foundation_date', 
    'change_country_flag', 'change_dominant_species', 'change_government', 'change_leader_class', 
    'change_leader_portrait', 'change_pc', 'change_planet_size', 'change_situation_target', 
    'change_species', 'change_species_characteristics', 'change_species_portrait', 
    'change_variable', 'check_casus_belli_valid', 'check_planet_employment', 'clear_blocker', 
    'clear_blockers', 'clear_custom_ruler_and_heir_titles', 'clear_deposits', 'clear_ethos', 
    'clear_fleet_actions', 'clear_global_event_target', 'clear_global_event_targets', 
    'clear_intel_report', 'clear_orders', 'clear_planet_modifiers', 'clear_planet_purge_type', 
    'clear_relations', 'clear_resources', 'clear_uncharted_space', 'clear_variable', 'clone_leader', 
    'close_branch_office', 'complete_crisis_objective', 'complete_deed', 'complete_special_project', 
    'complete_tutorial_step', 'conquer', 'convert_to_specialist', 'copy_ascension_perks_from', 
    'copy_ethos_and_authority', 'copy_flags_and_variables_from', 'copy_random_tech_from', 
    'copy_techs_from', 'copy_traditions_from', 'cosmic_storm_event', 
    'cosmic_storm_influence_field_event', 'country_add_ethic', 'country_event', 
    'country_list_tooltip', 'country_remove_ethic', 'create_ambient_object', 
    'create_archaeological_site', 'create_army', 'create_army_transport', 'create_bypass', 
    'create_cluster', 'create_colony', 'create_cosmic_storm', 'create_cosmic_storm_influence_field', 
    'create_country', 'create_espionage_asset', 'create_fleet', 'create_fleet_from_naval_cap', 
    'create_leader', 'create_message', 'create_military_fleet', 'create_mining_station', 
    'create_nebula', 'create_patron_relation', 'create_point_of_interest', 'create_pop', 
    'create_pop_group', 'create_rebels', 'create_research_station', 'create_saved_leader', 
    'create_ship', 'create_ship_design', 'create_smaller_size_creature_in_fleet', 'create_species', 
    'create_starbase', 'custom_tooltip_with_params', 'damage_army', 'damage_ship', 
    'date_distortion', 'deactivate_fog_machine', 'declare_war', 'decrease_council_size', 
    'delete_dimensional_fleet', 'delete_fleet', 'delete_fleet_naval_cap', 'delete_megastructure', 
    'delete_ship', 'destroy_ambient_object', 'destroy_and_spawn_debris_for', 
    'destroy_archaeological_site', 'destroy_astral_rift', 'destroy_colony', 'destroy_cosmic_storm', 
    'destroy_cosmic_storm_influence_field', 'destroy_country', 'destroy_espionage_asset', 
    'destroy_espionage_operation', 'destroy_fleet', 'destroy_fleet_naval_cap', 
    'destroy_psionic_aura', 'destroy_ship', 'destroy_situation', 'disable_building', 'dismantle', 
    'displace_pop_amount', 'dissolve_federation', 'divide_variable', 'downgrade_all_buildings', 
    'downgrade_buildings_of_type', 'effect_on_blob', 'enable_faction_of_type', 
    'enable_galactic_market', 'enable_mission', 'enable_on_market', 
    'enable_patron_first_contact_project', 'enable_special_project', 'end_all_treaties_with', 
    'end_event_chain', 'end_fleet_contract', 'end_rivalry', 'end_truce', 'endgame_telemetry', 
    'espionage_operation_event', 'establish_branch_office', 'establish_communications', 
    'establish_communications_no_message', 'establish_contact', 'every_active_first_contact', 
    'every_agreement', 'every_ambient_object', 'every_archaeological_site', 'every_associate', 
    'every_astral_rift', 'every_attacker', 'every_available_debris', 'every_bypass', 
    'every_bypass_in_system', 'every_combatant_fleet', 'every_controlled_fleet', 
    'every_controlled_planet', 'every_controlled_ship', 'every_cosmic_storm', 
    'every_cosmic_storm_end_position', 'every_cosmic_storm_start_position', 'every_council_member', 
    'every_country', 'every_country_neighbor_to_system', 'every_defender', 'every_deposit', 
    'every_enslaved_species', 'every_envoy', 'every_espionage_asset', 'every_espionage_operation', 
    'every_exhibit', 'every_existing_species_traits', 'every_federation', 'every_federation_ally', 
    'every_first_contact', 'every_fleet_in_orbit', 'every_fleet_in_system', 'every_galaxy_fleet', 
    'every_galaxy_planet', 'every_galaxy_sector', 'every_galaxy_species', 'every_galcom_member', 
    'every_ground_combat_attacker', 'every_ground_combat_defender', 'every_job_pop_group', 
    'every_megastructure', 'every_member', 'every_moon', 'every_neighbor_country', 
    'every_neighbor_system', 'every_neighbor_system_euclidean', 
    'every_observed_pre_ftl_within_border', 'every_orbital_station', 'every_owned_army', 
    'every_owned_design', 'every_owned_fleet', 'every_owned_leader', 'every_owned_megastructure', 
    'every_owned_nonprimary_starbase', 'every_owned_planet', 'every_owned_pop_group', 
    'every_owned_pop_job', 'every_owned_pop_species', 'every_owned_sector', 'every_owned_ship', 
    'every_owned_species', 'every_owned_starbase', 'every_owned_storm_influence_field', 
    'every_planet_army', 'every_planet_within_border', 'every_playable_country', 
    'every_pool_leader', 'every_pop_faction', 'every_pre_ftl_within_border', 'every_relation', 
    'every_rim_system', 'every_rival_country', 'every_ship_in_system', 'every_situation', 
    'every_species_pop_group', 'every_spynetwork', 'every_starbase_in_system', 'every_subject', 
    'every_system', 'every_system_added_to_storm', 'every_system_ambient_object', 
    'every_system_colony', 'every_system_in_cluster', 
    'every_system_in_cosmic_storm_influence_field', 'every_system_megastructure', 
    'every_system_planet', 'every_system_removed_from_storm', 'every_system_with_aura', 
    'every_system_within_border', 'every_system_within_storm', 'every_targeting_situation', 
    'every_trait_available_for_species', 'every_trait_of_species', 'every_war', 
    'every_war_participant', 'exile_leader_as', 'expire_site_event', 
    'export_modifier_duration_to_variable', 'export_modifier_to_variable', 
    'export_resource_income_to_variable', 'export_resource_maximum_to_variable', 
    'export_resource_stockpile_to_variable', 'export_trigger_value_to_variable', 
    'fill_astral_rift_event_pool', 'finish_all_researches', 'finish_astral_rift', 
    'finish_council_agenda', 'finish_current_operation_stage', 'finish_current_stage', 
    'finish_first_contact', 'finish_site', 'finish_terraformation', 'finish_upgrade', 
    'fire_on_action', 'first_contact_event', 'fleet_action_research_special_project', 'fleet_event', 
    'floor_variable', 'for', 'force_add_civic', 'force_faction_evaluation', 'force_remove_civic', 
    'freeze_leader_age', 'get_galaxy_setup_value', 'get_trade_data', 'give_culling_rewards', 
    'give_dna', 'give_fleet', 'give_specimen', 'give_technology', 'go_to_next_pre_ftl_age', 
    'guarantee_country', 'hidden_effect', 'increase_council_size', 'integrate_species', 'inverse', 
    'join_alliance', 'join_war', 'join_war_on_side', 'kill_assigned_pop_amount', 
    'kill_exiled_leader', 'kill_leader', 'kill_pop_group', 'leader_event', 'leave_alliance', 
    'link_to', 'link_wormholes', 'lock_bypass', 'lock_storm_in_place', 'locked_random_list', 
    'log_error', 'make_special_trade', 'merge_species', 'modify_army', 'modify_species', 
    'modulo_variable', 'move_system', 'multiply_crisis_strength', 'multiply_variable', 
    'must_scavenge/must_research', 'mutate_species', 'name', 'observer_event', 'open_shroud_tab', 
    'order_forced_return', 'ordered_active_first_contact', 'ordered_agreement', 
    'ordered_ambient_object', 'ordered_archaeological_site', 'ordered_associate', 
    'ordered_astral_rift', 'ordered_attacker', 'ordered_available_debris', 'ordered_bypass', 
    'ordered_bypass_in_system', 'ordered_combatant_fleet', 'ordered_controlled_fleet', 
    'ordered_controlled_planet', 'ordered_controlled_ship', 'ordered_cosmic_storm', 
    'ordered_cosmic_storm_end_position', 'ordered_cosmic_storm_start_position', 
    'ordered_council_member', 'ordered_country', 'ordered_country_neighbor_to_system', 
    'ordered_defender', 'ordered_deposit', 'ordered_enslaved_species', 'ordered_envoy', 
    'ordered_espionage_asset', 'ordered_espionage_operation', 'ordered_exhibit', 
    'ordered_existing_species_traits', 'ordered_federation', 'ordered_federation_ally', 
    'ordered_first_contact', 'ordered_fleet_in_orbit', 'ordered_fleet_in_system', 
    'ordered_galaxy_fleet', 'ordered_galaxy_planet', 'ordered_galaxy_sector', 
    'ordered_galaxy_species', 'ordered_galcom_member', 'ordered_ground_combat_attacker', 
    'ordered_ground_combat_defender', 'ordered_job_pop_group', 'ordered_megastructure', 
    'ordered_member', 'ordered_moon', 'ordered_neighbor_country', 'ordered_neighbor_system', 
    'ordered_neighbor_system_euclidean', 'ordered_observed_pre_ftl_within_border', 
    'ordered_orbital_station', 'ordered_owned_army', 'ordered_owned_design', 'ordered_owned_fleet', 
    'ordered_owned_leader', 'ordered_owned_megastructure', 'ordered_owned_nonprimary_starbase', 
    'ordered_owned_planet', 'ordered_owned_pop_group', 'ordered_owned_pop_job', 
    'ordered_owned_pop_species', 'ordered_owned_sector', 'ordered_owned_ship', 
    'ordered_owned_species', 'ordered_owned_starbase', 'ordered_owned_storm_influence_field', 
    'ordered_planet_army', 'ordered_planet_within_border', 'ordered_playable_country', 
    'ordered_pool_leader', 'ordered_pop_faction', 'ordered_pre_ftl_within_border', 
    'ordered_relation', 'ordered_rim_system', 'ordered_rival_country', 'ordered_ship_in_system', 
    'ordered_situation', 'ordered_species_pop_group', 'ordered_spynetwork', 
    'ordered_starbase_in_system', 'ordered_subject', 'ordered_system', 
    'ordered_system_added_to_storm', 'ordered_system_ambient_object', 'ordered_system_colony', 
    'ordered_system_in_cosmic_storm_influence_field', 'ordered_system_megastructure', 
    'ordered_system_planet', 'ordered_system_removed_from_storm', 'ordered_system_with_aura', 
    'ordered_system_within_border', 'ordered_system_within_storm', 'ordered_targeting_situation', 
    'ordered_trait_available_for_species', 'ordered_trait_of_species', 'ordered_war', 
    'ordered_war_participant', 'owned_fleet_list_tooltip', 'owned_leader_list_tooltip', 
    'owned_planet_list_tooltip', 'owned_pop_faction_list_tooltip', 'pass_debris_ownership', 
    'pass_resolution', 'pass_resolution_no_cooldown', 'pass_targeted_resolution', 
    'perform_astral_action_unlock_check', 'planet_event', 'play_sound', 'pop_change_ethic', 
    'pop_event', 'pop_faction_event', 'pop_force_add_ethic', 'pop_group_event', 'pop_remove_ethic', 
    'prevent_anomaly', 'progress_all_researches', 'prolong_fleet_contract', 'propose_resolution', 
    'queue_actions', 'random', 'random_active_first_contact', 'random_agreement', 
    'random_ambient_object', 'random_archaeological_site', 'random_associate', 'random_astral_rift', 
    'random_attacker', 'random_available_debris', 'random_bypass', 'random_bypass_in_system', 
    'random_combatant_fleet', 'random_controlled_fleet', 'random_controlled_planet', 
    'random_controlled_ship', 'random_cosmic_storm', 'random_cosmic_storm_end_position', 
    'random_cosmic_storm_start_position', 'random_council_member', 'random_country', 
    'random_country_neighbor_to_system', 'random_defender', 'random_deposit', 
    'random_enslaved_species', 'random_envoy', 'random_espionage_asset', 
    'random_espionage_operation', 'random_exhibit', 'random_existing_species_traits', 
    'random_federation', 'random_federation_ally', 'random_first_contact', 'random_fleet_in_orbit', 
    'random_fleet_in_system', 'random_galaxy_fleet', 'random_galaxy_planet', 'random_galaxy_sector', 
    'random_galaxy_species', 'random_galcom_member', 'random_ground_combat_attacker', 
    'random_ground_combat_defender', 'random_job_pop_group', 'random_list', 'random_megastructure', 
    'random_member', 'random_moon', 'random_neighbor_country', 'random_neighbor_system', 
    'random_neighbor_system_euclidean', 'random_observed_pre_ftl_within_border', 
    'random_orbital_station', 'random_owned_army', 'random_owned_design', 'random_owned_fleet', 
    'random_owned_leader', 'random_owned_megastructure', 'random_owned_nonprimary_starbase', 
    'random_owned_planet', 'random_owned_pop_group', 'random_owned_pop_job', 
    'random_owned_pop_species', 'random_owned_sector', 'random_owned_ship', 'random_owned_species', 
    'random_owned_starbase', 'random_owned_storm_influence_field', 'random_planet_army', 
    'random_planet_within_border', 'random_playable_country', 'random_pool_leader', 
    'random_pop_faction', 'random_pre_ftl_within_border', 'random_relation', 'random_rim_system', 
    'random_rival_country', 'random_ship_in_system', 'random_situation', 'random_species_pop_group', 
    'random_spynetwork', 'random_starbase_in_system', 'random_subject', 'random_system', 
    'random_system_added_to_storm', 'random_system_ambient_object', 'random_system_colony', 
    'random_system_in_cosmic_storm_influence_field', 'random_system_megastructure', 
    'random_system_planet', 'random_system_removed_from_storm', 'random_system_with_aura', 
    'random_system_within_border', 'random_system_within_storm', 'random_targeting_situation', 
    'random_trait_available_for_species', 'random_trait_of_species', 'random_war', 
    'random_war_participant', 'randomize_flag_symbol', 'reanimate_space_fauna', 
    'recalculate_storm_influence_field', 'recruitable', 'reduce_hp', 'reduce_hp_percent', 
    'reduce_shield', 'refresh_accords', 'refresh_auto_generated_ship_designs', 
    'refresh_leader_pool', 'refresh_portraits', 'refresh_psionic_aura_type', 
    'refresh_species_rights', 'refuse_covenant', 'release_vivarium_fauna', 
    'release_vivarium_fauna_count', 'remove_agreement_flag', 'remove_all_armies', 
    'remove_all_buildings', 'remove_all_districts', 'remove_all_negative_traits', 
    'remove_all_positive_traits', 'remove_all_traits', 'remove_ambient_object_flag', 
    'remove_archaeology_flag', 'remove_army', 'remove_army_flag', 'remove_ascension_perk', 
    'remove_associate_member', 'remove_astral_rift_flag', 'remove_auto_move_target', 
    'remove_building', 'remove_claims', 'remove_communications', 'remove_country_flag', 
    'remove_deposit', 'remove_deposit_flag', 'remove_design_flag', 'remove_district', 
    'remove_envoys_to', 'remove_espionage_asset_flag', 'remove_espionage_operation_flag', 
    'remove_favors', 'remove_federation_flag', 'remove_first_contact_flag', 'remove_fleet_flag', 
    'remove_from_empire_council', 'remove_from_federation', 'remove_from_galactic_community', 
    'remove_from_galactic_council', 'remove_global_flag', 'remove_global_ship_design', 
    'remove_holding', 'remove_hyperlane', 'remove_leader_flag', 'remove_megastructure', 
    'remove_megastructure_flag', 'remove_modifier', 'remove_notification_modifier', 
    'remove_opinion_modifier', 'remove_patron', 'remove_permanent_councillor', 'remove_planet', 
    'remove_planet_flag', 'remove_point_of_interest', 'remove_pop_amount', 
    'remove_pop_faction_flag', 'remove_pop_flag', 'remove_pop_group_flag', 'remove_random_building', 
    'remove_random_district', 'remove_random_starbase_building', 'remove_random_starbase_module', 
    'remove_relation_flag', 'remove_relic', 'remove_saved_leader', 'remove_secret_fealty', 
    'remove_sector_flag', 'remove_ship_design', 'remove_ship_flag', 'remove_situation_flag', 
    'remove_species_flag', 'remove_specimen', 'remove_spynetwork_flag', 'remove_stage_modifier', 
    'remove_star_flag', 'remove_starbase_building', 'remove_starbase_component', 
    'remove_starbase_flag', 'remove_starbase_module', 'remove_terrified', 'remove_tradition', 
    'remove_tradition_tree', 'remove_trait', 'remove_war_flag', 'remove_war_participant', 
    'remove_zone', 'rename_species', 'renew_bypass_lock', 'repair_all_buildings', 'repair_amount', 
    'repair_armor_amount', 'repair_armor_percentage', 'repair_building', 'repair_percentage', 
    'repair_shield_amount', 'repair_shield_percentage', 'repair_ship', 'replace_patron', 
    'reroll_deposits', 'reroll_planet_modifiers', 'reroll_random', 'reset_current_stage', 
    'reset_event_chain_counter', 'reset_growth', 'reset_killed_ship_designs', 
    'reset_policy_cooldowns', 'reset_years_of_peace', 'resettle_pop', 'restore_country_backup_data', 
    'return_leader_from_exile', 'revert_accords', 'roll_ai_preferred_patron', 'room_name_override', 
    'round_variable', 'round_variable_to_closest', 'ruin_building', 'run_ai_strategic_data', 
    'run_ai_strategic_war_data', 'sacrifice_assigned_pop_amount', 'sacrifice_pop_group', 
    'save_event_target_as', 'save_global_event_target_as', 'scale_pop_amount', 'select_decision', 
    'set_adjective', 'set_advisor_active', 'set_age', 'set_aggro_range', 
    'set_aggro_range_measure_from', 'set_agreement_flag', 'set_agreement_preset', 
    'set_agreement_terms', 'set_ai_personality', 'set_ai_preferred_patron', 
    'set_allow_subjects_to_join', 'set_ambient_object_flag', 'set_archaeology_flag', 
    'set_army_flag', 'set_asteroid_belt', 'set_astral_rift_flag', 'set_attunement', 
    'set_aura_intensity', 'set_auto_upgrade_components', 'set_awareness', 'set_built_species', 
    'set_capital', 'set_citizenship_type', 'set_city_graphical_culture', 'set_cloaking_active', 
    'set_closed_borders', 'set_colonization_controls', 'set_colony_type', 'set_confused', 
    'set_controller', 'set_cooldown', 'set_cosmic_storm', 'set_council_agenda', 
    'set_council_emergency_measures', 'set_council_position', 'set_council_position_title_female', 
    'set_council_position_title_male', 'set_council_position_to_council', 'set_council_size', 
    'set_council_veto', 'set_country_code_flags', 'set_country_flag', 'set_country_type', 
    'set_crisis_sound', 'set_current_stage', 'set_custodian_term_days', 
    'set_custom_capital_location', 'set_deposit', 'set_deposit_flag', 'set_design_flag', 
    'set_diplomacy_action_setting', 'set_disable_at_health', 'set_disabled', 
    'set_emergency_fund_active', 'set_emergency_fund_contribution_rate', 
    'set_emperor_can_change_council_members', 'set_empire_flag', 'set_empire_name', 
    'set_equal_voting_power', 'set_espionage_asset_flag', 'set_espionage_operation_flag', 
    'set_espionage_operation_progress_locked', 'set_event_locked', 'set_faction_auto_delete', 
    'set_faction_extorted', 'set_faction_hostility', 'set_faction_needs_colony', 
    'set_fauna_fleet_growth_stance', 'set_federation_flag', 'set_federation_law', 
    'set_federation_leader', 'set_federation_settings', 'set_federation_succession_term', 
    'set_federation_succession_type', 'set_federation_type', 'set_female_heir_title', 
    'set_female_ruler_title', 'set_first_contact_flag', 'set_first_contact_stage', 
    'set_fleet_bombardment_stance', 'set_fleet_flag', 'set_fleet_formation', 'set_fleet_settings', 
    'set_fleet_stance', 'set_formation_scale', 'set_free_migration', 'set_galactic_custodian', 
    'set_galactic_defense_force', 'set_galactic_emperor', 'set_gender', 'set_global_flag', 
    'set_government_cooldown', 'set_graphical_culture', 'set_habitability_trait', 'set_halted', 
    'set_heir', 'set_home_base', 'set_hostile', 'set_immortal', 'set_leader', 'set_leader_flag', 
    'set_leader_tier', 'set_living_standard', 'set_location', 'set_male_heir_title', 
    'set_male_ruler_title', 'set_market_leader', 'set_megastructure_flag', 'set_mia', 
    'set_mia_return_delay', 'set_migration_controls', 'set_military_service_type', 'set_mission', 
    'set_mission_counter', 'set_name', 'set_next_astral_rift_event', 
    'set_only_leader_builds_fleets', 'set_origin', 'set_owner', 'set_patron_first_contact_state', 
    'set_planet_entity', 'set_planet_flag', 'set_planet_name', 'set_planet_purge_type', 
    'set_planet_size', 'set_planetary_ascension_tier', 'set_player', 'set_policy', 
    'set_policy_cooldown', 'set_pop_faction', 'set_pop_faction_flag', 'set_pop_flag', 
    'set_pop_group_flag', 'set_population_controls', 'set_pre_ftl_age', 'set_purge_type', 
    'set_relation_flag', 'set_resource', 'set_ring', 'set_rule_can_subject_be_integrated', 
    'set_rule_can_subject_do_diplomacy', 'set_rule_can_subject_expand', 'set_rule_can_subject_vote', 
    'set_rule_join_overlord_wars', 'set_rule_join_subject_wars', 'set_rule_subject_has_access', 
    'set_rule_subject_has_sensors', 'set_ruler_title_female', 'set_ruler_title_male', 
    'set_saved_date', 'set_sector_capital', 'set_sector_flag', 'set_ship_construction_type', 
    'set_ship_design', 'set_ship_flag', 'set_ship_prefix', 'set_site_progress_locked', 
    'set_situation_approach', 'set_situation_flag', 'set_situation_locked', 
    'set_situation_progress', 'set_skill', 'set_slavery_type', 'set_spawn_system_batch', 
    'set_species_flag', 'set_species_homeworld', 'set_species_identity', 'set_spynetwork_flag', 
    'set_star_class', 'set_star_flag', 'set_starbase_building', 'set_starbase_flag', 
    'set_starbase_module', 'set_starbase_size', 'set_storm_flag', 'set_subject_of', 'set_surveyed', 
    'set_terraform_progress', 'set_terrified_by', 'set_timed_agreement_flag', 
    'set_timed_ambient_object_flag', 'set_timed_archaeology_flag', 'set_timed_army_flag', 
    'set_timed_country_flag', 'set_timed_deposit_flag', 'set_timed_espionage_asset_flag', 
    'set_timed_espionage_operation_flag', 'set_timed_federation_flag', 
    'set_timed_first_contact_flag', 'set_timed_fleet_flag', 'set_timed_global_flag', 
    'set_timed_leader_flag', 'set_timed_megastructure_flag', 'set_timed_planet_flag', 
    'set_timed_pop_faction_flag', 'set_timed_pop_flag', 'set_timed_pop_group_flag', 
    'set_timed_relation_flag', 'set_timed_sector_flag', 'set_timed_ship_flag', 
    'set_timed_situation_flag', 'set_timed_species_flag', 'set_timed_spynetwork_flag', 
    'set_timed_star_flag', 'set_timed_starbase_flag', 'set_timed_war_flag', 'set_trade_conversions', 
    'set_truce', 'set_tutorial_level', 'set_update_modifiers_batch', 'set_variable', 
    'set_variable_to_random_value', 'set_visited', 'set_war_flag', 'set_war_goal', 
    'set_years_served', 'shift_ethic', 'ship_event', 'should_add_ship_to_debris', 'situation_event', 
    'spawn_astral_rift', 'spawn_custom_debris', 'spawn_megastructure', 'spawn_natural_wormhole', 
    'spawn_planet', 'spawn_psionic_aura', 'spawn_random_storm', 'spawn_system', 'starbase_event', 
    'start_astral_action_cooldown', 'start_colony', 'start_situation', 'start_storm_area_placing', 
    'start_terraform_process', 'start_terraform_progress', 'steal_relic', 'steal_specimens', 
    'stop_crisis_sound', 'stop_mission', 'stop_terraform_process', 'store_country_backup_data', 
    'storm_apply_aftermath_modifier', 'subtract_variable', 'system_event', 'tooltip', 
    'transfer_galactic_defense_force_fleets', 'transfer_pop_amount', 'trigger_megastructure_icon', 
    'unassign_espionage_asset', 'unassign_leader', 'unemploy_pop', 'unlock_council_selection', 
    'unlock_council_slots', 'unlock_exhibit', 'unset_cosmic_storm', 'upgrade_megastructure_to', 
    'validate_and_repair_planet_buildings_and_districts', 'validate_planet_buildings_and_districts', 
    'weighted_random_owned_pop_group', 'weights', 'while', 'win',
})

# 所有 Scopes
SCOPES_IDENTIFIERS = frozenset({
    'alliance', 'archaeological_site', 'army_leader', 'assembling_species', 'associated_federation', 
    'astral_rift', 'attacker', 'aura_owner', 'background_planet', 'branch_office_owner', 
    'built_species', 'capital_scope', 'capital_star', 'contact_country', 'controller', 'creator', 
    'declining_species', 'defender', 'design', 'envoy_location_country', 'excavator_fleet', 
    'explorer', 'federation', 'federation_leader', 'fleet', 'founder_species', 'from', 'fromfrom', 
    'fromfromfrom', 'fromfromfromfrom', 'galactic_custodian', 'galactic_emperor', 'growing_species', 
    'heir', 'home_planet', 'instigator', 'last_added_deposit', 'last_created_ambient_object', 
    'last_created_army', 'last_created_cosmic_storm', 'last_created_cosmic_storm_influence_field', 
    'last_created_country', 'last_created_design', 'last_created_fleet', 'last_created_leader', 
    'last_created_pop_faction', 'last_created_ship', 'last_created_species', 'last_created_system', 
    'leader', 'lock_country', 'mining_station', 'no_scope', 'observation_outpost', 
    'observation_outpost_owner', 'orbit', 'orbital_defence', 'orbital_station', 'overlord', 'owner', 
    'owner_main_species', 'owner_or_space_owner', 'owner_species', 'planet', 'planet_owner', 
    'pop_faction', 'prev', 'prevprev', 'prevprevprev', 'prevprevprevprev', 'research_station', 
    'reverse_first_contact', 'root', 'ruler', 'sector', 'sector_capital', 'ship_growth_stage', 
    'solar_system', 'space_owner', 'spawner_planet', 'species', 'spynetwork', 'star', 'starbase', 
    'storm_influence_field', 'system_star', 'target', 'target_system', 'this', 'unhappiest_pop',
})
